### ISSUE TITLE
bug: The demo is frozen sometimes on multi-turn 

### ISSUE THREAD

**Issue by tikikun** [janhq/ichigo#105] opened 2024-11-11 05:20 UTC
## Problem

@nguyenhoangthuan99 can you help me populate the bug description?

**Comment by nguyenhoangthuan99** [comment] 2024-11-11 05:43
## Problem
- Ichigo demo frontend disables record button randomly during the conversation.


## Root cause
The record button will disabled when 
```
 (isPlayingAudio || isLoading) && "pointer-events-none opacity-50"
)}
```
![image](https://github.com/user-attachments/assets/78d10b01-805b-48f6-8ded-0af4849929c8)

Sometimes, the chat API doesn't respond any message, this lead to frontend will be blocked.
![image](https://github.com/user-attachments/assets/887d9f9d-aaf5-4407-88cf-d5b431df976f)

Faisal fixed this bug on this [commit](https://github.com/homebrewltd/ichigo-demo/pull/6/commits/a87675ff4f837194d35bc72dae2d3d2f6838d6b3). Now, the fixed frontend version is deployed in [ichigo.homebrew.ltd](ichigo.homebrew.ltd)
cc @urmauur

**Comment by nguyenhoangthuan99** [comment] 2024-11-25 03:34
Faisal has fixed this issue. I will close this issue

**Closed by nguyenhoangthuan99** 2024-11-25 03:34 UTC
Labels: type: bug
